security:
    firewalls:
        frontend:
            pattern: ^/* 
            provider: usuarios 
            anonymous: ~ 
            form_login:
                login_path: usuario_login 
                check_path: usuario_login_check
            logout:
                path: usuario_logout
                
    access_control:
        - { path: ^/(es|en)/usuario/(login|registro), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en)/usuario/*, roles: ROLE_USUARIO }
        
    providers:
        usuarios:
            entity: { class: AppBundle\Entity\Usuario, property: email }
            
    encoders:
        AppBundle\Entity\Usuario: plaintext
